name: Go Build Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build with Go
      run: |
        # Устанавливаем Go без setup-go action
        curl -L https://golang.org/dl/go1.25.2.linux-amd64.tar.gz | sudo tar -C /usr/local -xz
        echo "/usr/local/go/bin" >> $GITHUB_PATH
        go version
        go build ./cmd/main.go