name: Go CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./cmd/...

    - name: Test
      run: go test -v ./...

  # Опционально - сборка артефактов для деплоя
  build-artifacts:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build binary
      run: go build -o myapp ./cmd
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp-binary
        path: myapp